# fly.toml app configuration file generated for brain-bridge on 2023-05-30T11:18:56-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "brain-bridge"
primary_region = "iad"

[http_service]
  internal_port = 4001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
