# fly.toml app configuration file generated for sw-chatbot on 2023-05-13T17:56:21-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sw-chatbot"
primary_region = "atl"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[mounts]
  source="audio"
  destination="/audio"
[env]
  PRIMARY_REGION = "atl"

[[services]]
  protocol = "tcp"
  internal_port = 4000
  min_machines_running = 0
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
